Repository braille-systems/learn-braille, pull requests merged in 2020-09, with the labels that each got.

#251 Refactor
  .github/workflows/android.yml
  app/src/androidTest/java/com/github/braillesystems/learnbraille/data/repository/ActionsRepositoryTest.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/db/LearnBrailleDatabase.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/dsl/Courses.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/dsl/DataStorage.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/dsl/Defs.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/dsl/Lessons.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/dsl/Materials.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/dsl/Users.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/entities/Actions.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/entities/BrailleDots.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/entities/Cards.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/entities/Common.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/entities/CoursePositions.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/entities/Courses.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/entities/Decks.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/entities/KnownMaterials.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/entities/Lessons.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/entities/MaterialData.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/entities/Materials.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/entities/StepAnnotations.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/entities/StepData.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/entities/StepHasAnnotations.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/entities/Steps.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/entities/Users.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/repository/ActionsRepository.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/repository/BrowserRepository.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/repository/MaterialsRepository.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/repository/PracticeRepository.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/repository/PreferenceRepository.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/repository/TheoryRepository.kt
  app/src/main/java/com/github/braillesystems/learnbraille/res/Data.kt
  app/src/main/java/com/github/braillesystems/learnbraille/res/Materials.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/DotsChecker.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/practice/CardViewModel.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/stats/StatsFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/utils/Utils.kt
  app/src/main/java/com/github/braillesystems/learnbraille/utils/_Android.kt
  app/src/main/java/com/github/braillesystems/learnbraille/utils/_Kotlin.kt
  app/src/test/java/com/github/braillesystems/learnbraille/data/dsl/DslTest.kt
  app/src/test/java/com/github/braillesystems/learnbraille/utils/_KotlinTest.kt
Labels: refactoring

#254 #250 move NumberSign to markers
  app/src/main/java/com/github/braillesystems/learnbraille/res/Data.kt
  app/src/main/java/com/github/braillesystems/learnbraille/res/GolubinaCourse.kt
  app/src/main/java/com/github/braillesystems/learnbraille/res/Materials.kt
  app/src/main/java/com/github/braillesystems/learnbraille/res/TestCourse.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/practice/CardViewModel.kt
  app/src/main/res/values/strings.xml
Labels: lessons, practice

#256 #255 disable artifacts generation when workflow cancelled
  .github/workflows/android.yml
Labels: bug, testing

#252 Feature/241 greek latin
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  CONTRIBUTING.md
  app/src/androidTest/java/com/github/braillesystems/learnbraille/res/ResourceTest.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/db/LearnBrailleDatabase.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/repository/PreferenceRepository.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/repository/TheoryRepository.kt
  app/src/main/java/com/github/braillesystems/learnbraille/res/Data.kt
  app/src/main/java/com/github/braillesystems/learnbraille/res/GolubinaCourse.kt
  app/src/main/java/com/github/braillesystems/learnbraille/res/Materials.kt
  app/src/main/java/com/github/braillesystems/learnbraille/res/TestCourse.kt
  app/src/main/java/com/github/braillesystems/learnbraille/res/_DSL.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/browser/SymbolViewFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/practice/CardFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/InputSymbolFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/ShowSymbolFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/views/BrailleDotsView.kt
  app/src/main/java/com/github/braillesystems/learnbraille/utils/_Kotlin.kt
  app/src/main/res/layout/fragment_card.xml
  app/src/main/res/layout/fragment_lessons_input_symbol.xml
  app/src/main/res/layout/fragment_lessons_show_symbol.xml
  app/src/main/res/layout/fragment_symbol_view.xml
  app/src/main/res/values-sw320dp/dimens.xml
  app/src/main/res/values-sw360dp/dimens.xml
  app/src/main/res/values-sw400dp/dimens.xml
  app/src/main/res/values-sw600dp/dimens.xml
  app/src/main/res/values-sw720dp/dimens.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/settings_hierarchy.xml
  build.gradle
Labels: enhancement, interface, lessons, practice

#269 Feature/reflected dots
  app/src/androidTest/java/com/github/braillesystems/learnbraille/data/repository/MaterialsRepositoryTest.kt
  app/src/main/java/com/github/braillesystems/learnbraille/LearnBrailleApplication.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/dsl/Courses.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/entities/StepData.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/repository/PreferenceRepository.kt
  app/src/main/java/com/github/braillesystems/learnbraille/res/GolubinaCourse.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/Messages.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/AbstractFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/AbstractFragmentWithHelp.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/DotsChecker.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/browser/BrowserFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/browser/MarkerViewFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/browser/SymbolViewFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/exit/ExitFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/help/HelpFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/menu/MenuFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/practice/CardFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/practice/CardViewModel.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/practice/DecksListFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/settings/SettingsFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/stats/StatsFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/lessons/LessonsListFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/AbstractStepFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/info/AbstractInfoStepFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/info/FirstInfoFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/info/InfoFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/info/LastInfoFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/input/AbstractInputStepFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/input/InputDotsFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/input/InputMarkerFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/input/InputSymbolFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/show/AbstractShowStepFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/show/ShowDotsFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/show/ShowMarkerFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/show/ShowSymbolFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/views/BigLetterView.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/views/BrailleDotsView.kt
  app/src/main/java/com/github/braillesystems/learnbraille/utils/Utils.kt
  app/src/main/java/com/github/braillesystems/learnbraille/utils/_Kotlin.kt
  app/src/main/res/drawable/ic_flip_white_24dp.xml
  app/src/main/res/drawable/left_border.xml
  app/src/main/res/drawable/right_border.xml
  app/src/main/res/layout/braille_dots_view.xml
  app/src/main/res/layout/fragment_card.xml
  app/src/main/res/layout/fragment_lessons_input_dots.xml
  app/src/main/res/layout/fragment_lessons_input_marker.xml
  app/src/main/res/layout/fragment_lessons_input_symbol.xml
  app/src/main/res/layout/fragment_lessons_show_dots.xml
  app/src/main/res/layout/fragment_lessons_show_marker.xml
  app/src/main/res/layout/fragment_lessons_show_symbol.xml
  app/src/main/res/layout/fragment_marker_view.xml
  app/src/main/res/layout/fragment_symbol_view.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/settings_hierarchy.xml
  app/src/test/java/com/github/braillesystems/learnbraille/utils/_KotlinTest.kt
  detekt-config.yml
Labels: accessibility, enhancement, interface

#274 Fix/exit button
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/exit/ExitFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/utils/_Android.kt
Labels: bug
