Repository braille-systems/learn-braille, pull requests merged in 2020-08, with the labels that each got.

#238 #237 resolve naming clash (Data & data)
  app/src/androidTest/java/com/github/braillesystems/learnbraille/data/dsl/DslTest.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/dsl/DataStorage.kt
Labels: bug

#242 Fix/blinking title
  app/src/main/res/navigation/navigation.xml
  app/src/main/res/values/strings.xml
Labels: bug, refactoring

#244 #185 add access to meta info from info steps dsl
  app/src/androidTest/java/com/github/braillesystems/learnbraille/data/dsl/DslTest.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/dsl/DataStorage.kt
  app/src/main/java/com/github/braillesystems/learnbraille/res/GolubinaCourse.kt
Labels: lessons
