Repository braille-systems/learn-braille, pull requests merged in 2020-05, with the labels that each got.

#126 Fix redundant buzz in lessons
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/lessons/AbstractInputLesson.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/lessons/InputDotsFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/lessons/InputSymbolFragment.kt
Labels: lessons

#89 Feature/voice response exit
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/exit/ExitFragment.kt
  android/app/src/main/res/values/strings.xml
Labels: accessibility

#127 feature/settings_ui
  android/app/build.gradle
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/menu/MenuFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/settings/SettingsFragment.kt
  android/app/src/main/res/layout/fragment_menu.xml
  android/app/src/main/res/navigation/navigation.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
  android/app/src/main/res/xml/settings_hierarchy.xml
Labels: interface

#129 Feature/serial input
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/DotsChecker.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/MainActivity.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/practice/PracticeFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/serial/UsbParser.java
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/serial/UsbSerial.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/serial/UsbService.java
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/serial/UsbSignalHandler.java
  android/app/src/main/res/values/strings.xml
Labels: enhancement, practice, refactoring

#136 DSL: add docs and examples in tests
  android/app/src/androidTest/java/com/github/braillesystems/learnbraille/DslTest.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/res/Data.kt
Labels: documentation, testing

#142 Feature/disable annotated steps
  android/app/src/main/java/com/github/braillesystems/learnbraille/data/entities/Steps.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/data/repository/TheoryRepository.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/res/Data.kt
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/xml/settings_hierarchy.xml
Labels: help and docs, interface, lessons

#145 Refactor checked access
  android/app/src/main/java/com/github/braillesystems/learnbraille/data/repository/PreferenceRepository.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/brailletrainer/BrailleTrainer.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/utils/SpeechRecognition.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/utils/Utils.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/utils/_Kotlin.kt
Labels: refactoring

#146 Add custom symbol hint support
  android/app/src/main/java/com/github/braillesystems/learnbraille/data/dsl/Materials.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/data/entities/Materials.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/data/repository/PreferenceRepository.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/_DotsChecker.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/practice/CardFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/InputDotsFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/InputSymbolFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/utils/SpeechRecognition.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/utils/Utils.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/utils/_Android.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/utils/_Kotlin.kt
  android/app/src/main/res/values/strings.xml
Labels: accessibility, interface

#143 6.3 add voice permission
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/menu/MenuFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/utils/SpeechRecognition.kt
  android/app/src/main/res/values/strings.xml
Labels: accessibility, enhancement

#149 6.18 fixed context invalidation
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/_DotsChecker.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/utils/_Kotlin.kt
Labels: bug

#148 Feature/fill lessons
  android/app/src/main/java/com/github/braillesystems/learnbraille/LearnBrailleApplication.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/data/db/Database.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/res/Data.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/res/GolubinaCourse.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/res/Materials.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/res/TestCourse.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/res/_DSL.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/_DotsChecker.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/menu/MenuFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/FirstInfoFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/InfoFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/InputDotsFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/LastInfoFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/ShowDotsFragment.kt
  android/app/src/main/res/values/strings.xml
Labels: accessibility, enhancement, lessons

#151 6.14 Fix/talkback traversal
  android/app/src/main/java/com/github/braillesystems/learnbraille/data/repository/PreferenceRepository.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/views/BrailleDotsView.kt
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/xml/settings_hierarchy.xml
Labels: accessibility

#152 Remove titles & improve input accessibility
  android/app/src/main/java/com/github/braillesystems/learnbraille/res/Materials.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/res/_DSL.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/Messages.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/views/BigLetterView.kt
  android/app/src/main/res/layout/fragment_lesson_first_info.xml
  android/app/src/main/res/layout/fragment_lesson_last_info.xml
  android/app/src/main/res/layout/fragment_lessons_info.xml
  android/app/src/main/res/layout/fragment_lessons_input_dots.xml
  android/app/src/main/res/layout/fragment_lessons_input_symbol.xml
  android/app/src/main/res/layout/fragment_lessons_show_dots.xml
  android/app/src/main/res/layout/fragment_lessons_show_symbol.xml
  android/app/src/main/res/layout/fragment_practice.xml
  android/app/src/main/res/values/strings.xml
Labels: interface

#153 Feature/check dots on fly
  android/app/src/main/java/com/github/braillesystems/learnbraille/data/repository/PreferenceRepository.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/DotsChecker.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/practice/CardFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/practice/CardViewModel.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/InputDotsFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/InputSymbolFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/views/BrailleDotsView.kt
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/xml/settings_hierarchy.xml
Labels: accessibility, interface

#154 Feature/steps toolbar
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/AbstractFragmentWithHelp.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/AbstractStepFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/FirstInfoFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/InfoFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/InputDotsFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/InputSymbolFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/ShowDotsFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/ShowSymbolFragment.kt
  android/app/src/main/res/layout/fragment_lesson_first_info.xml
  android/app/src/main/res/layout/fragment_lessons_info.xml
  android/app/src/main/res/layout/fragment_lessons_input_dots.xml
  android/app/src/main/res/layout/fragment_lessons_input_symbol.xml
  android/app/src/main/res/layout/fragment_lessons_show_dots.xml
  android/app/src/main/res/layout/fragment_lessons_show_symbol.xml
  android/app/src/main/res/menu/help_menu.xml
  android/app/src/main/res/menu/steps_menu.xml
  android/app/src/main/res/values/strings.xml
Labels: interface

#147 Feature/lessons list
  android/app/build.gradle
  android/app/src/main/java/com/github/braillesystems/learnbraille/LearnBrailleApplication.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/data/entities/Lessons.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/data/entities/Steps.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/data/repository/TheoryRepository.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/menu/MenuFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/TheoryFreeNavigation.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/lessons/LessonsListFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/AbstractStepFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/FirstInfoFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/InfoFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/InputDotsFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/InputSymbolFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/InputViewModel.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/LastInfoFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/ShowDotsFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/ShowSymbolFragment.kt
  android/app/src/main/res/layout/fragment_lessons_input_dots.xml
  android/app/src/main/res/layout/fragment_lessons_input_symbol.xml
  android/app/src/main/res/layout/fragment_lessons_list.xml
  android/app/src/main/res/layout/lessons_list_item.xml
  android/app/src/main/res/navigation/navigation.xml
  android/app/src/main/res/values/strings.xml
Labels: interface, lessons

#158 6.19 fix wrong letter in lessons
  android/app/src/main/java/com/github/braillesystems/learnbraille/res/GolubinaCourse.kt
Labels: bug, lessons

#165 Fix settings navigation
  android/app/build.gradle
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/greeting/GreetingFragment.kt
  android/app/src/main/res/navigation/navigation.xml
Labels: bug

#171 7.5 fix multiple touches navigation
  android/app/build.gradle
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/AbstractFragmentWithHelp.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/MainActivity.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/exit/ExitFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/menu/MenuFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/TheoryFreeNavigation.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/AbstractStepFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/utils/SpeechRecognition.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/utils/Utils.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/utils/_Android.kt
Labels: bug

#173 fix/color_contrast
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/practice/DecksList.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/lessons/LessonsListFragment.kt
  android/app/src/main/res/values/colors.xml
Labels: accessibility

#176 Doc/helps
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/AbstractStepFragment.kt
  android/app/src/main/res/values/strings.xml
Labels: enhancement

#175 Feature/checked announcements
  android/app/src/main/java/com/github/braillesystems/learnbraille/data/repository/PreferenceRepository.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/AbstractFragmentWithHelp.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/exit/ExitFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/help/HelpFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/practice/CardFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/FirstInfoFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/InfoFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/InputDotsFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/InputSymbolFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/LastInfoFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/ShowDotsFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/ShowSymbolFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/utils/Utils.kt
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/xml/settings_hierarchy.xml
Labels: accessibility

#177 Fix/gconsole errors
  android/app/build.gradle
  android/app/src/main/java/com/github/braillesystems/learnbraille/utils/Utils.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/utils/_Android.kt
Labels: bug

#179 feature/list_icons
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/practice/DecksList.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/lessons/LessonsListFragment.kt
  android/app/src/main/res/drawable/locked.xml
  android/app/src/main/res/drawable/unlocked.xml
  android/app/src/main/res/layout/decks_list_item.xml
  android/app/src/main/res/layout/lessons_list_item.xml
  android/app/src/main/res/values/dimens.xml
Labels: interface

#182 Narrow side buttons + info text to full screen height
  android/app/src/main/res/layout/fragment_card.xml
  android/app/src/main/res/layout/fragment_help.xml
  android/app/src/main/res/layout/fragment_lesson_first_info.xml
  android/app/src/main/res/layout/fragment_lesson_last_info.xml
  android/app/src/main/res/layout/fragment_lessons_info.xml
  android/app/src/main/res/layout/fragment_lessons_input_dots.xml
  android/app/src/main/res/layout/fragment_lessons_input_symbol.xml
  android/app/src/main/res/values-sw320dp/dimens.xml
  android/app/src/main/res/values-sw360dp/dimens.xml
  android/app/src/main/res/values-sw400dp/dimens.xml
  android/app/src/main/res/values-sw600dp/dimens.xml
  android/app/src/main/res/values-sw720dp/dimens.xml
  android/app/src/main/res/values/dimens.xml
  android/app/src/main/res/values/styles.xml
Labels: interface

#181 Hide availability icons if use only known disabled
  android/app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/practice/DecksList.kt
  android/app/src/main/res/values/strings.xml
Labels: interface
