Repository braille-systems/learn-braille, pull requests merged in 2020-04, with the labels that each got.

#38 3.19 feature/practice/hint
  android/app/build.gradle
  android/app/src/main/java/ru/spbstu/amd/learnbraille/LearnBrailleApplication.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/Util.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/BrailleDots.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/practice/PracticeFragment.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/practice/PracticeViewModel.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/serial/UsbSerial.kt
  android/app/src/main/res/drawable/practice_btn_shape.xml
  android/app/src/main/res/drawable/practice_hint_btn_shape.xml
  android/app/src/main/res/layout/fragment_practice.xml
  android/app/src/main/res/values/strings.xml
  android/build.gradle
Labels: enhancement

#41 Fixed 39
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/entities/BrailleDots.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/entities/Symbols.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/lessons/LessonStepFragment.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/lessons/LessonStepViewModel.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/menu/MenuFragment.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/practice/PracticeFragment.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/practice/PracticeViewModel.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/views/ButtonsView.kt
  android/app/src/main/res/layout/fragment_lesson_step.xml
  android/app/src/main/res/navigation/navigation.xml
Labels: bugfix

#53 Feature/help in menu
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/menu/MenuFragment.kt
  android/app/src/main/res/layout/fragment_menu.xml
  android/app/src/main/res/values/strings.xml
Labels: enhancement

#44 Lessons
  android/app/src/androidTest/java/ru/spbstu/amd/learnbraille/LearnBrailleDatabaseTest.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/LearnBrailleApplication.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/Util.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/DataUtil.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/Database.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/entities/BrailleDots.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/entities/StepData.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/entities/Steps.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/entities/Symbols.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/entities/UserKnowsSymbol.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/entities/UserPassedStep.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/steps/AllSteps.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/steps/DebugLessons.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/steps/Lesson1.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/steps/LessonFirst.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/steps/LessonLast.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/AbstractFragmentWithHelp.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/DotsChecker.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/ScreensUtil.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/Util.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/exit/ExitFragment.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/greeting/GreetingFragment.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/help/HelpFragment.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/lessons/AbstractLesson.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/lessons/FirstInfoFragment.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/lessons/InfoFragment.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/lessons/InputDotsFragment.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/lessons/InputSymbolFragment.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/lessons/InputViewModel.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/lessons/LastInfoFragment.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/lessons/LessonsUtil.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/lessons/ShowDotsFragment.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/lessons/ShowSymbolFragment.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/menu/MenuFragment.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/practice/PracticeFragment.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/practice/PracticeViewModel.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/views/ButtonsView.kt
  android/app/src/main/res/drawable/practice_btn_shape.xml
  android/app/src/main/res/drawable/practice_hint_btn_shape.xml
  android/app/src/main/res/layout/fragment_lesson_first_info.xml
  android/app/src/main/res/layout/fragment_lesson_last_info.xml
  android/app/src/main/res/layout/fragment_lessons_info.xml
  android/app/src/main/res/layout/fragment_lessons_input_dots.xml
  android/app/src/main/res/layout/fragment_lessons_input_symbol.xml
  android/app/src/main/res/layout/fragment_lessons_show_dots.xml
  android/app/src/main/res/layout/fragment_lessons_show_symbol.xml
  android/app/src/main/res/layout/fragment_menu.xml
  android/app/src/main/res/navigation/navigation.xml
  android/app/src/main/res/values/strings.xml
Labels: enhancement

#64 Fix DB prepopulation
  android/app/build.gradle
  android/app/src/androidTest/java/ru/spbstu/amd/learnbraille/LearnBrailleDatabaseTest.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/LearnBrailleApplication.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/MainActivity.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/Util.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/Database.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/Executors.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/entities/Lessons.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/entities/Steps.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/entities/Symbols.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/entities/User.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/entities/UserKnowsSymbol.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/entities/UserPassedStep.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/Lessons.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/steps/DebugLessons.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/steps/Lesson1.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/steps/Lesson2.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/symbols/AllSymbols.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/symbols/NonLetters.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/symbols/RuLetters.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/ScreensUtil.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/lessons/LessonsUtil.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/menu/MenuFragment.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/practice/PracticeViewModel.kt
  android/app/src/main/res/values/strings.xml
  android/build.gradle
Labels: bugfix, enhancement

#71 Update README.md
  README.md
Labels: documentation

#74 4.8 replace question mark icon for help section
  android/app/src/main/java/com/github/braillesystems/learnbraille/screens/DotsChecker.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/screens/lessons/AbstractLesson.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/screens/lessons/InputDotsFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/screens/lessons/InputSymbolFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/screens/lessons/LessonsUtil.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/screens/practice/PracticeFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/views/BrailleDotsView.kt
  android/app/src/main/res/drawable/action_menu_help_button.xml
  android/app/src/main/res/drawable/tmp_help_button.xml
  android/app/src/main/res/menu/help_menu.xml
Labels: enhancement

#72 Feature/icon beta
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/icon_beta-playstore.png
  android/app/src/main/res/mipmap-anydpi-v26/icon_beta.xml
  android/app/src/main/res/mipmap-anydpi-v26/icon_beta_round.xml
  android/app/src/main/res/mipmap-hdpi/icon_beta.png
  android/app/src/main/res/mipmap-hdpi/icon_beta_background.png
  android/app/src/main/res/mipmap-hdpi/icon_beta_foreground.png
  android/app/src/main/res/mipmap-hdpi/icon_beta_round.png
  android/app/src/main/res/mipmap-mdpi/icon_beta.png
  android/app/src/main/res/mipmap-mdpi/icon_beta_background.png
  android/app/src/main/res/mipmap-mdpi/icon_beta_foreground.png
  android/app/src/main/res/mipmap-mdpi/icon_beta_round.png
  android/app/src/main/res/mipmap-xhdpi/icon_beta.png
  android/app/src/main/res/mipmap-xhdpi/icon_beta_background.png
  android/app/src/main/res/mipmap-xhdpi/icon_beta_foreground.png
  android/app/src/main/res/mipmap-xhdpi/icon_beta_round.png
  android/app/src/main/res/mipmap-xxhdpi/icon_beta.png
  android/app/src/main/res/mipmap-xxhdpi/icon_beta_background.png
  android/app/src/main/res/mipmap-xxhdpi/icon_beta_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/icon_beta_round.png
  android/app/src/main/res/mipmap-xxxhdpi/icon_beta.png
  android/app/src/main/res/mipmap-xxxhdpi/icon_beta_background.png
  android/app/src/main/res/mipmap-xxxhdpi/icon_beta_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/icon_beta_round.png
  android/app/src/main/res/values/icon_beta_background.xml
Labels: enhancement

#75 4.11 add autosizing textview and html tags
  android/app/build.gradle
  android/app/src/main/java/com/github/braillesystems/learnbraille/screens/help/HelpFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/util/ScreensUtil.kt
  android/app/src/main/res/layout/fragment_help.xml
  android/app/src/main/res/values/strings.xml
Labels: enhancement

#76 Feature/lessons content
  android/app/src/main/java/com/github/braillesystems/learnbraille/LearnBrailleApplication.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/database/Database.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/res/russian/Lessons.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/res/russian/steps/Lesson1.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/res/russian/steps/Lesson2.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/res/russian/steps/LessonFirst.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/res/russian/steps/LessonLast.kt
Labels: enhancement

#73 Feature/material design
  android/app/build.gradle
  android/app/src/main/java/com/github/braillesystems/learnbraille/screens/lessons/InputSymbolFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/screens/lessons/ShowSymbolFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/screens/practice/PracticeFragment.kt
  android/app/src/main/res/drawable/action_menu_help_button.xml
  android/app/src/main/res/drawable/checked_round_checkbox.xml
  android/app/src/main/res/drawable/navigate_left.xml
  android/app/src/main/res/drawable/navigate_right.xml
  android/app/src/main/res/drawable/practice_btn_shape.xml
  android/app/src/main/res/drawable/practice_hint_btn_shape.xml
  android/app/src/main/res/drawable/to_progress.xml
  android/app/src/main/res/drawable/unchecked_round_checkbox.xml
  android/app/src/main/res/layout/fragment_exit.xml
  android/app/src/main/res/layout/fragment_greeting.xml
  android/app/src/main/res/layout/fragment_lesson_first_info.xml
  android/app/src/main/res/layout/fragment_lesson_last_info.xml
  android/app/src/main/res/layout/fragment_lessons_info.xml
  android/app/src/main/res/layout/fragment_lessons_input_dots.xml
  android/app/src/main/res/layout/fragment_lessons_input_symbol.xml
  android/app/src/main/res/layout/fragment_lessons_show_dots.xml
  android/app/src/main/res/layout/fragment_lessons_show_symbol.xml
  android/app/src/main/res/layout/fragment_menu.xml
  android/app/src/main/res/layout/fragment_practice.xml
  android/app/src/main/res/mipmap-anydpi-v26/icon_beta.xml
  android/app/src/main/res/mipmap-anydpi-v26/icon_beta_round.xml
  android/app/src/main/res/values-sw600dp/dimens.xml
  android/app/src/main/res/values-sw720dp/dimens.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/dimens.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
Labels: enhancement

#79 Change input steps logic
  android/app/src/main/java/com/github/braillesystems/learnbraille/screens/DotsChecker.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/screens/lessons/AbstractInputLesson.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/screens/lessons/InputDotsFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/screens/lessons/InputSymbolFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/screens/lessons/ShowDotsFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/screens/practice/PracticeFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/views/BrailleDotsView.kt
Labels: enhancement

#81 4.21 fix wrong letter in lessons
  android/app/src/main/java/com/github/braillesystems/learnbraille/res/russian/steps/Lesson2.kt
Labels: bugfix

#85 Fix text formatting
  android/app/src/main/java/com/github/braillesystems/learnbraille/database/Database.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/res/russian/steps/LessonLast.kt
  android/app/src/main/res/values/strings.xml
Labels: enhancement

#84 4.3 change class name for talkback
  android/app/src/main/java/com/github/braillesystems/learnbraille/database/entities/Symbols.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/views/BrailleDotsView.kt
  android/app/src/main/res/layout/braille_dots_view.xml
Labels: bugfix

#83 4.12 make toast on each new letter in practice
  android/app/src/main/java/com/github/braillesystems/learnbraille/LearnBrailleApplication.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/database/entities/BrailleDots.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/screens/DotsChecker.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/screens/lessons/AbstractInputLesson.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/screens/lessons/InputDotsFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/screens/lessons/InputSymbolFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/screens/menu/MenuFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/screens/practice/PracticeFragment.kt
  android/app/src/main/res/values/strings.xml
Labels: enhancement

#97 Style fix and toasts refactoring
  android/app/src/main/java/com/github/braillesystems/learnbraille/LearnBrailleApplication.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/database/entities/BrailleDots.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/database/entities/StepData.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/screens/lessons/AbstractInputLesson.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/screens/menu/MenuFragment.kt
Labels: enhancement

#119 Create database.md
  database.md
Labels: documentation, refactoring

#115 Navigation graph proposal
  navigation.md
Labels: enhancement, interface

#122 5.7 fix google play redirection
  android/app/src/main/java/com/github/braillesystems/learnbraille/screens/menu/MenuFragment.kt
  android/app/src/main/java/com/github/braillesystems/learnbraille/util/Util.kt
  android/app/src/main/res/layout/fragment_menu.xml
  android/app/src/main/res/values/strings.xml
Labels: bug, interface
