Repository braille-systems/learn-braille, pull requests merged in 2020-07, with the labels that each got.

#194 #189 make pronounce Help messages passage-by-passage
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/help/HelpFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/views/HelpView.kt
  app/src/main/res/layout/fragment_help.xml
  app/src/main/res/values-sw600dp/dimens.xml
  app/src/main/res/values-sw720dp/dimens.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: accessibility

#197 Feature/extended accessibility settings
  app/src/main/java/com/github/braillesystems/learnbraille/data/repository/PreferenceRepository.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/menu/MenuFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/practice/CardFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/AbstractInfoStepFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/AbstractStepFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/FirstInfoFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/InfoFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/InputDotsFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/InputSymbolFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/LastInfoFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/ShowDotsFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/ShowSymbolFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/utils/_Android.kt
  app/src/main/res/layout/fragment_card.xml
  app/src/main/res/layout/fragment_lesson_first_info.xml
  app/src/main/res/layout/fragment_lesson_last_info.xml
  app/src/main/res/layout/fragment_lessons_info.xml
  app/src/main/res/layout/fragment_lessons_input_dots.xml
  app/src/main/res/layout/fragment_lessons_input_symbol.xml
  app/src/main/res/layout/fragment_lessons_show_dots.xml
  app/src/main/res/layout/fragment_lessons_show_symbol.xml
  app/src/main/res/values-sw320dp/dimens.xml
  app/src/main/res/values-sw360dp/dimens.xml
  app/src/main/res/values-sw400dp/dimens.xml
  app/src/main/res/values-sw600dp/dimens.xml
  app/src/main/res/values-sw720dp/dimens.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/settings_hierarchy.xml
Labels: accessibility, interface

#205 Fix hint text in steps with dots
  app/src/main/java/com/github/braillesystems/learnbraille/data/entities/BrailleDots.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/Messages.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/practice/CardFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/InputSymbolFragment.kt
  app/src/main/res/values/strings.xml
Labels: accessibility, lessons

#206 #200 Feature/200 replace dot step title
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/AbstractStepFragment.kt
  app/src/main/res/values/strings.xml
Labels: accessibility, help and docs, interface, lessons

#211 Update AbstractStepFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/AbstractStepFragment.kt
Labels: accessibility

#212 Fix/ui
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/help/HelpFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/AbstractStepFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/views/HelpView.kt
  app/src/main/java/com/github/braillesystems/learnbraille/utils/Utils.kt
  app/src/main/java/com/github/braillesystems/learnbraille/utils/_Android.kt
  app/src/main/java/com/github/braillesystems/learnbraille/utils/_Kotlin.kt
  app/src/main/res/xml/settings_hierarchy.xml
Labels: help and docs, interface

#219 #193 add references to Golubina for each letter
  app/src/main/java/com/github/braillesystems/learnbraille/data/db/Database.kt
  app/src/main/java/com/github/braillesystems/learnbraille/res/GolubinaCourse.kt
Labels: lessons

#226 make cards less repeating
  app/src/androidTest/java/com/github/braillesystems/learnbraille/utils/_KotlinTest.kt
  app/src/main/java/com/github/braillesystems/learnbraille/res/TestCourse.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/practice/CardViewModel.kt
  app/src/main/java/com/github/braillesystems/learnbraille/utils/_Kotlin.kt
Labels: practice

#231 #230 update AdditionalAnnouncements setting description
  app/src/main/java/com/github/braillesystems/learnbraille/data/repository/PreferenceRepository.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/settings_hierarchy.xml
Labels: accessibility

#232 #216 display stats in TableView
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/stats/StatsFragment.kt
  app/src/main/res/layout/fragment_stats.xml
  app/src/main/res/layout/fragment_stats_table.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: interface

#225 Feature/stats
  app/src/androidTest/java/com/github/braillesystems/learnbraille/data/repository/ActionsRepositoryTest.kt
  app/src/main/java/com/github/braillesystems/learnbraille/LearnBrailleApplication.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/db/Database.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/dsl/Courses.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/entities/Actions.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/repository/ActionsRepository.kt
  app/src/main/java/com/github/braillesystems/learnbraille/data/repository/TheoryRepository.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/help/HelpFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/menu/MenuFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/practice/CardViewModel.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/stats/StatsFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/TheoryFreeNavigation.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/lessons/LessonsListFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/AbstractStepFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/utils/Utils.kt
  app/src/main/java/com/github/braillesystems/learnbraille/utils/_Android.kt
  app/src/main/java/com/github/braillesystems/learnbraille/utils/_Kotlin.kt
  app/src/main/res/layout/fragment_menu.xml
  app/src/main/res/layout/fragment_stats.xml
  app/src/main/res/layout/fragment_stats_table.xml
  app/src/main/res/navigation/navigation.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement, interface
