Repository braille-systems/learn-braille, pull requests merged in 2020-03, with the labels that each got.

#1 Feature/init room
  android/app/build.gradle
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/BrailleDots.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/Database.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/Executors.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/Language.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/Symbols.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/practice/PracticeFragment.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/practice/PracticeViewModel.kt
  android/app/src/main/res/layout/fragment_practice.xml
  android/app/src/main/res/navigation/navigation.xml
  android/build.gradle
Labels: enhancement

#3 Update README after repository move
  README.md
Labels: documentation

#2 Make cleanup
  doc/report2019/bibliography.tex
  doc/report2019/body.tex
  doc/report2019/main.tex
  doc/report2019/parts/img/McCullochPittsNeuron.png
  doc/report2019/parts/img/bioneuron.png
  doc/report2019/parts/img/neuron.png
  doc/report2019/parts/img/nnet.png
  doc/report2019/parts/img/nnet_boundary.jpg
  doc/report2019/parts/img/perceptronOutput.png
  doc/report2019/parts/nnet.tex
  doc/report2019/parts/perceptron.tex
  doc/report2019/titlepage.tex
  releases/0.1.ru.md
  src/.gitignore
  src/classify/__init__.py
  src/classify/classifuncs.py
  src/classify/logreg.py
  src/classify/nnet.py
  src/classify/nnet/matlab/MAIN.m
  src/classify/nnet/matlab/costFunction.m
  src/classify/nnet/matlab/data2.txt
  src/classify/nnet/matlab/fmincg.m
  src/classify/nnet/matlab/plotCostProjection.m
  src/classify/nnet/matlab/plotDecisionBoundary.m
  src/classify/nnet/matlab/predict.m
  src/classify/nnet/matlab/randInitializeWeights.m
  src/classify/nnet/matlab/readme.md
  src/classify/nnet/matlab/sigmoid.m
  src/classify/sigm_neuron/matlab/MAIN.m
  src/classify/sigm_neuron/matlab/costFunction.m
  src/classify/sigm_neuron/matlab/data.txt
  src/classify/sigm_neuron/matlab/gradientDescent.m
  src/classify/sigm_neuron/matlab/plotCostProjection.m
  src/classify/sigm_neuron/matlab/plotDecisionBoundary.m
  src/classify/sigm_neuron/matlab/predict.m
  src/classify/sigm_neuron/matlab/readme.md
  src/classify/sigm_neuron/matlab/sigmoid.m
  src/test/__init__.py
  src/test/classifuncTest.py
  src/test/nnetTest.py
Labels: enhancement

#7 Update CONTRIBUTING.ru.md
  CONTRIBUTING.ru.md
Labels: documentation

#10 Make menu start fragment
  android/app/src/main/res/navigation/navigation.xml
Labels: enhancement

#15 Refactor/lessons/ui arch
  android/app/src/main/java/ru/spbstu/amd/learnbraille/MainActivity.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/lessons/LessonStepFragment.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/lessons/LessonStepViewModel.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/menu/MenuFragment.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/practice/PracticeFragment.kt
  android/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  android/app/src/main/res/drawable/checked_round_checkbox.xml
  android/app/src/main/res/drawable/ic_launcher_background.xml
  android/app/src/main/res/drawable/round_checkbox.xml
  android/app/src/main/res/drawable/unchecked_round_checkbox.xml
  android/app/src/main/res/layout/fragment_lesson_step.xml
  android/app/src/main/res/layout/fragment_menu.xml
  android/app/src/main/res/layout/fragment_show_step_inner.xml
  android/app/src/main/res/layout/fragment_text_step.xml
  android/app/src/main/res/layout/fragment_text_step_inner.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/navigation/navigation.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
Labels: enhancement

#19 Fill all
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/Database.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/Language.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/Lessons.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/Steps.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/Symbols.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/User.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/Lessons.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/Users.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/steps/AllSteps.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/steps/Lesson1.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/steps/Lesson2.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/symbols/AllSymbols.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/symbols/NonLetters.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/symbols/RuLetters.kt
Labels: enhancement

#17 Add lessons scheme
  android/app/src/androidTest/java/ru/spbstu/amd/learnbraille/ExampleInstrumentedTest.kt
  android/app/src/androidTest/java/ru/spbstu/amd/learnbraille/LearnBrailleDatabaseTest.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/BrailleDots.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/Database.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/Language.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/Lessons.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/StepData.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/Steps.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/Symbols.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/User.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/UserKnowsSymbol.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/UserPassedStep.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/Util.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/Lessons.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/Users.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/steps/AllSteps.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/steps/Lesson1.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/steps/Lesson2.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/symbols/AllSymbols.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/symbols/NonLetters.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/symbols/RuLetters.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/practice/PracticeViewModel.kt
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/ru/spbstu/amd/learnbraille/ExampleUnitTest.kt
Labels: enhancement

#23 Add step descriptions in code
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/StepData.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/Util.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/steps/Lesson1.kt
Labels: documentation

#27 3.6 add view model to lessons
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/BrailleDots.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/StepData.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/Steps.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/database/User.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/steps/AllSteps.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/res/russian/steps/LessonLast.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/lessons/LessonStepFragment.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/lessons/LessonStepViewModel.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/practice/PracticeFragment.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/practice/PracticeViewModel.kt
Labels: enhancement

#28 Show toast on practice if db is not yet initialized
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/practice/PracticeFragment.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/practice/PracticeViewModel.kt
  android/app/src/main/res/values/strings.xml
Labels: bugfix

#26 3.10 toolbar functionality + help
  android/app/src/main/java/ru/spbstu/amd/learnbraille/MainActivity.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/exit/ExitFragment.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/greeting/GreetingFragment.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/help/HelpFragment.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/lessons/LessonStepFragment.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/menu/MenuFragment.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/practice/PracticeFragment.kt
  android/app/src/main/java/ru/spbstu/amd/learnbraille/screens/practice/PracticeViewModel.kt
  android/app/src/main/res/drawable/tmp_help_button.xml
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/fragment_exit.xml
  android/app/src/main/res/layout/fragment_help.xml
  android/app/src/main/res/layout/fragment_lesson_step.xml
  android/app/src/main/res/layout/fragment_menu.xml
  android/app/src/main/res/layout/fragment_practice.xml
  android/app/src/main/res/menu/help_menu.xml
  android/app/src/main/res/navigation/navigation.xml
  android/app/src/main/res/values/strings.xml
Labels: enhancement

#30 readme: add links to most important docs
  CONTRIBUTING.ru.md
  README.md
Labels: documentation

#31 feature/accessibility_fix
  android/app/src/main/res/layout/braille_dots.xml
Labels: enhancement

#33 feature/toolbar
  android/app/src/main/res/menu/help_menu.xml
Labels: enhancement

#34 3.16 change color pallet
  android/app/src/main/res/layout/fragment_exit.xml
  android/app/src/main/res/layout/fragment_greeting.xml
  android/app/src/main/res/layout/fragment_lesson_step.xml
  android/app/src/main/res/values/colors.xml
Labels: enhancement
