Repository braille-systems/learn-braille, pull requests merged in 2020-10, with the labels that each got.

#283 Feature/278 text on dots
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/browser/MarkerViewFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/browser/SymbolViewFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/practice/CardFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/AbstractStepFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/input/AbstractInputStepFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/show/AbstractShowStepFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/views/BrailleDotsView.kt
  app/src/main/res/drawable/round_checkbox.xml
  app/src/main/res/drawable/to_progress.xml
  app/src/main/res/layout/braille_dots_view.xml
  app/src/main/res/values-sw320dp/dimens.xml
  app/src/main/res/values-sw360dp/dimens.xml
  app/src/main/res/values-sw400dp/dimens.xml
  app/src/main/res/values-sw600dp/dimens.xml
  app/src/main/res/values-sw720dp/dimens.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement, interface, lessons, practice

#286 Fix hints in input dots step
  app/src/main/java/com/github/braillesystems/learnbraille/ui/Messages.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/input/AbstractInputStepFragment.kt
  app/src/main/java/com/github/braillesystems/learnbraille/ui/screens/theory/steps/input/InputDotsFragment.kt
  app/src/main/res/values/strings.xml
Labels: accessibility, bug, help and docs

#288 #287 rename theory -> learning
  app/src/main/res/values/strings.xml
Labels: interface
